// Generated by gencpp from file sushi_bot/Microphone.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_MICROPHONE_H
#define SUSHI_BOT_MESSAGE_MICROPHONE_H

#include <ros/service_traits.h>


#include <sushi_bot/MicrophoneRequest.h>
#include <sushi_bot/MicrophoneResponse.h>


namespace sushi_bot
{

struct Microphone
{

typedef MicrophoneRequest Request;
typedef MicrophoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Microphone
} // namespace sushi_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushi_bot::Microphone > {
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::sushi_bot::Microphone&) { return value(); }
};

template<>
struct DataType< ::sushi_bot::Microphone > {
  static const char* value()
  {
    return "sushi_bot/Microphone";
  }

  static const char* value(const ::sushi_bot::Microphone&) { return value(); }
};


// service_traits::MD5Sum< ::sushi_bot::MicrophoneRequest> should match
// service_traits::MD5Sum< ::sushi_bot::Microphone >
template<>
struct MD5Sum< ::sushi_bot::MicrophoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::Microphone >::value();
  }
  static const char* value(const ::sushi_bot::MicrophoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::MicrophoneRequest> should match
// service_traits::DataType< ::sushi_bot::Microphone >
template<>
struct DataType< ::sushi_bot::MicrophoneRequest>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::Microphone >::value();
  }
  static const char* value(const ::sushi_bot::MicrophoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushi_bot::MicrophoneResponse> should match
// service_traits::MD5Sum< ::sushi_bot::Microphone >
template<>
struct MD5Sum< ::sushi_bot::MicrophoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::Microphone >::value();
  }
  static const char* value(const ::sushi_bot::MicrophoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::MicrophoneResponse> should match
// service_traits::DataType< ::sushi_bot::Microphone >
template<>
struct DataType< ::sushi_bot::MicrophoneResponse>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::Microphone >::value();
  }
  static const char* value(const ::sushi_bot::MicrophoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_MICROPHONE_H
