// Generated by gencpp from file sushi_bot/MicrophoneResponse.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_MICROPHONERESPONSE_H
#define SUSHI_BOT_MESSAGE_MICROPHONERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushi_bot
{
template <class ContainerAllocator>
struct MicrophoneResponse_
{
  typedef MicrophoneResponse_<ContainerAllocator> Type;

  MicrophoneResponse_()
    : response()  {
    }
  MicrophoneResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MicrophoneResponse_

typedef ::sushi_bot::MicrophoneResponse_<std::allocator<void> > MicrophoneResponse;

typedef boost::shared_ptr< ::sushi_bot::MicrophoneResponse > MicrophoneResponsePtr;
typedef boost::shared_ptr< ::sushi_bot::MicrophoneResponse const> MicrophoneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushi_bot::MicrophoneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sushi_bot::MicrophoneResponse_<ContainerAllocator1> & lhs, const ::sushi_bot::MicrophoneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sushi_bot::MicrophoneResponse_<ContainerAllocator1> & lhs, const ::sushi_bot::MicrophoneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sushi_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::sushi_bot::MicrophoneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushi_bot/MicrophoneResponse";
  }

  static const char* value(const ::sushi_bot::MicrophoneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::sushi_bot::MicrophoneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MicrophoneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushi_bot::MicrophoneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushi_bot::MicrophoneResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_MICROPHONERESPONSE_H
