// Generated by gencpp from file sushi_bot/RobotTaskRequest.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_ROBOTTASKREQUEST_H
#define SUSHI_BOT_MESSAGE_ROBOTTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushi_bot
{
template <class ContainerAllocator>
struct RobotTaskRequest_
{
  typedef RobotTaskRequest_<ContainerAllocator> Type;

  RobotTaskRequest_()
    : dish_name()
    , table_number()  {
    }
  RobotTaskRequest_(const ContainerAllocator& _alloc)
    : dish_name(_alloc)
    , table_number(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dish_name_type;
  _dish_name_type dish_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _table_number_type;
  _table_number_type table_number;





  typedef boost::shared_ptr< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotTaskRequest_

typedef ::sushi_bot::RobotTaskRequest_<std::allocator<void> > RobotTaskRequest;

typedef boost::shared_ptr< ::sushi_bot::RobotTaskRequest > RobotTaskRequestPtr;
typedef boost::shared_ptr< ::sushi_bot::RobotTaskRequest const> RobotTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushi_bot::RobotTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sushi_bot::RobotTaskRequest_<ContainerAllocator1> & lhs, const ::sushi_bot::RobotTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dish_name == rhs.dish_name &&
    lhs.table_number == rhs.table_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sushi_bot::RobotTaskRequest_<ContainerAllocator1> & lhs, const ::sushi_bot::RobotTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sushi_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f8352310bba5657999e4fadeced7a00";
  }

  static const char* value(const ::sushi_bot::RobotTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f8352310bba5657ULL;
  static const uint64_t static_value2 = 0x999e4fadeced7a00ULL;
};

template<class ContainerAllocator>
struct DataType< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushi_bot/RobotTaskRequest";
  }

  static const char* value(const ::sushi_bot::RobotTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string dish_name\n"
"string table_number\n"
;
  }

  static const char* value(const ::sushi_bot::RobotTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dish_name);
      stream.next(m.table_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushi_bot::RobotTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushi_bot::RobotTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "dish_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dish_name);
    s << indent << "table_number: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.table_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_ROBOTTASKREQUEST_H
