// Generated by gencpp from file sushi_bot/RobotTask.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_ROBOTTASK_H
#define SUSHI_BOT_MESSAGE_ROBOTTASK_H

#include <ros/service_traits.h>


#include <sushi_bot/RobotTaskRequest.h>
#include <sushi_bot/RobotTaskResponse.h>


namespace sushi_bot
{

struct RobotTask
{

typedef RobotTaskRequest Request;
typedef RobotTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotTask
} // namespace sushi_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushi_bot::RobotTask > {
  static const char* value()
  {
    return "3d9d08dba52c168a90cd568a864ab567";
  }

  static const char* value(const ::sushi_bot::RobotTask&) { return value(); }
};

template<>
struct DataType< ::sushi_bot::RobotTask > {
  static const char* value()
  {
    return "sushi_bot/RobotTask";
  }

  static const char* value(const ::sushi_bot::RobotTask&) { return value(); }
};


// service_traits::MD5Sum< ::sushi_bot::RobotTaskRequest> should match
// service_traits::MD5Sum< ::sushi_bot::RobotTask >
template<>
struct MD5Sum< ::sushi_bot::RobotTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::RobotTask >::value();
  }
  static const char* value(const ::sushi_bot::RobotTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::RobotTaskRequest> should match
// service_traits::DataType< ::sushi_bot::RobotTask >
template<>
struct DataType< ::sushi_bot::RobotTaskRequest>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::RobotTask >::value();
  }
  static const char* value(const ::sushi_bot::RobotTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushi_bot::RobotTaskResponse> should match
// service_traits::MD5Sum< ::sushi_bot::RobotTask >
template<>
struct MD5Sum< ::sushi_bot::RobotTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::RobotTask >::value();
  }
  static const char* value(const ::sushi_bot::RobotTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::RobotTaskResponse> should match
// service_traits::DataType< ::sushi_bot::RobotTask >
template<>
struct DataType< ::sushi_bot::RobotTaskResponse>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::RobotTask >::value();
  }
  static const char* value(const ::sushi_bot::RobotTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_ROBOTTASK_H
