// Generated by gencpp from file sushi_bot/TableStatus.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_TABLESTATUS_H
#define SUSHI_BOT_MESSAGE_TABLESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushi_bot
{
template <class ContainerAllocator>
struct TableStatus_
{
  typedef TableStatus_<ContainerAllocator> Type;

  TableStatus_()
    : status()
    , has_empty_plate(false)
    , timestamp()  {
    }
  TableStatus_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , has_empty_plate(false)
    , timestamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef uint8_t _has_empty_plate_type;
  _has_empty_plate_type has_empty_plate;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::sushi_bot::TableStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushi_bot::TableStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TableStatus_

typedef ::sushi_bot::TableStatus_<std::allocator<void> > TableStatus;

typedef boost::shared_ptr< ::sushi_bot::TableStatus > TableStatusPtr;
typedef boost::shared_ptr< ::sushi_bot::TableStatus const> TableStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushi_bot::TableStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushi_bot::TableStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sushi_bot::TableStatus_<ContainerAllocator1> & lhs, const ::sushi_bot::TableStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.has_empty_plate == rhs.has_empty_plate &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sushi_bot::TableStatus_<ContainerAllocator1> & lhs, const ::sushi_bot::TableStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sushi_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::TableStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::TableStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::TableStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::TableStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::TableStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::TableStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushi_bot::TableStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40a61210ebc44d54272f5bae65a7e206";
  }

  static const char* value(const ::sushi_bot::TableStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40a61210ebc44d54ULL;
  static const uint64_t static_value2 = 0x272f5bae65a7e206ULL;
};

template<class ContainerAllocator>
struct DataType< ::sushi_bot::TableStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushi_bot/TableStatus";
  }

  static const char* value(const ::sushi_bot::TableStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushi_bot::TableStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"bool has_empty_plate\n"
"time timestamp\n"
;
  }

  static const char* value(const ::sushi_bot::TableStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushi_bot::TableStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.has_empty_plate);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TableStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushi_bot::TableStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushi_bot::TableStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "has_empty_plate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_empty_plate);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_TABLESTATUS_H
