// Generated by gencpp from file sushi_bot/TaskAssignment.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_TASKASSIGNMENT_H
#define SUSHI_BOT_MESSAGE_TASKASSIGNMENT_H

#include <ros/service_traits.h>


#include <sushi_bot/TaskAssignmentRequest.h>
#include <sushi_bot/TaskAssignmentResponse.h>


namespace sushi_bot
{

struct TaskAssignment
{

typedef TaskAssignmentRequest Request;
typedef TaskAssignmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskAssignment
} // namespace sushi_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushi_bot::TaskAssignment > {
  static const char* value()
  {
    return "ba41c7c5d4e8b7cf1a6d4085ce149d1f";
  }

  static const char* value(const ::sushi_bot::TaskAssignment&) { return value(); }
};

template<>
struct DataType< ::sushi_bot::TaskAssignment > {
  static const char* value()
  {
    return "sushi_bot/TaskAssignment";
  }

  static const char* value(const ::sushi_bot::TaskAssignment&) { return value(); }
};


// service_traits::MD5Sum< ::sushi_bot::TaskAssignmentRequest> should match
// service_traits::MD5Sum< ::sushi_bot::TaskAssignment >
template<>
struct MD5Sum< ::sushi_bot::TaskAssignmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::TaskAssignment >::value();
  }
  static const char* value(const ::sushi_bot::TaskAssignmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::TaskAssignmentRequest> should match
// service_traits::DataType< ::sushi_bot::TaskAssignment >
template<>
struct DataType< ::sushi_bot::TaskAssignmentRequest>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::TaskAssignment >::value();
  }
  static const char* value(const ::sushi_bot::TaskAssignmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushi_bot::TaskAssignmentResponse> should match
// service_traits::MD5Sum< ::sushi_bot::TaskAssignment >
template<>
struct MD5Sum< ::sushi_bot::TaskAssignmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::TaskAssignment >::value();
  }
  static const char* value(const ::sushi_bot::TaskAssignmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::TaskAssignmentResponse> should match
// service_traits::DataType< ::sushi_bot::TaskAssignment >
template<>
struct DataType< ::sushi_bot::TaskAssignmentResponse>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::TaskAssignment >::value();
  }
  static const char* value(const ::sushi_bot::TaskAssignmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_TASKASSIGNMENT_H
