// Generated by gencpp from file sushi_bot/VerifyOrderRequest.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_VERIFYORDERREQUEST_H
#define SUSHI_BOT_MESSAGE_VERIFYORDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushi_bot
{
template <class ContainerAllocator>
struct VerifyOrderRequest_
{
  typedef VerifyOrderRequest_<ContainerAllocator> Type;

  VerifyOrderRequest_()
    : robot_id()
    , dish_name()  {
    }
  VerifyOrderRequest_(const ContainerAllocator& _alloc)
    : robot_id(_alloc)
    , dish_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dish_name_type;
  _dish_name_type dish_name;





  typedef boost::shared_ptr< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VerifyOrderRequest_

typedef ::sushi_bot::VerifyOrderRequest_<std::allocator<void> > VerifyOrderRequest;

typedef boost::shared_ptr< ::sushi_bot::VerifyOrderRequest > VerifyOrderRequestPtr;
typedef boost::shared_ptr< ::sushi_bot::VerifyOrderRequest const> VerifyOrderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator1> & lhs, const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.dish_name == rhs.dish_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator1> & lhs, const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sushi_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23ad89e0aa3b3164019025d5c28f7be2";
  }

  static const char* value(const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23ad89e0aa3b3164ULL;
  static const uint64_t static_value2 = 0x019025d5c28f7be2ULL;
};

template<class ContainerAllocator>
struct DataType< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushi_bot/VerifyOrderRequest";
  }

  static const char* value(const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_id \n"
"string dish_name\n"
;
  }

  static const char* value(const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.dish_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VerifyOrderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushi_bot::VerifyOrderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushi_bot::VerifyOrderRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
    s << indent << "dish_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dish_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_VERIFYORDERREQUEST_H
