// Generated by gencpp from file sushi_bot/VerifyOrderResponse.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_VERIFYORDERRESPONSE_H
#define SUSHI_BOT_MESSAGE_VERIFYORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushi_bot
{
template <class ContainerAllocator>
struct VerifyOrderResponse_
{
  typedef VerifyOrderResponse_<ContainerAllocator> Type;

  VerifyOrderResponse_()
    : success(false)  {
    }
  VerifyOrderResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VerifyOrderResponse_

typedef ::sushi_bot::VerifyOrderResponse_<std::allocator<void> > VerifyOrderResponse;

typedef boost::shared_ptr< ::sushi_bot::VerifyOrderResponse > VerifyOrderResponsePtr;
typedef boost::shared_ptr< ::sushi_bot::VerifyOrderResponse const> VerifyOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator1> & lhs, const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator1> & lhs, const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sushi_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushi_bot/VerifyOrderResponse";
  }

  static const char* value(const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VerifyOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushi_bot::VerifyOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushi_bot::VerifyOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_VERIFYORDERRESPONSE_H
