// Generated by gencpp from file sushi_bot/VerifyOrder.msg
// DO NOT EDIT!


#ifndef SUSHI_BOT_MESSAGE_VERIFYORDER_H
#define SUSHI_BOT_MESSAGE_VERIFYORDER_H

#include <ros/service_traits.h>


#include <sushi_bot/VerifyOrderRequest.h>
#include <sushi_bot/VerifyOrderResponse.h>


namespace sushi_bot
{

struct VerifyOrder
{

typedef VerifyOrderRequest Request;
typedef VerifyOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VerifyOrder
} // namespace sushi_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushi_bot::VerifyOrder > {
  static const char* value()
  {
    return "821c392785703a596b403147fefd576d";
  }

  static const char* value(const ::sushi_bot::VerifyOrder&) { return value(); }
};

template<>
struct DataType< ::sushi_bot::VerifyOrder > {
  static const char* value()
  {
    return "sushi_bot/VerifyOrder";
  }

  static const char* value(const ::sushi_bot::VerifyOrder&) { return value(); }
};


// service_traits::MD5Sum< ::sushi_bot::VerifyOrderRequest> should match
// service_traits::MD5Sum< ::sushi_bot::VerifyOrder >
template<>
struct MD5Sum< ::sushi_bot::VerifyOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::VerifyOrder >::value();
  }
  static const char* value(const ::sushi_bot::VerifyOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::VerifyOrderRequest> should match
// service_traits::DataType< ::sushi_bot::VerifyOrder >
template<>
struct DataType< ::sushi_bot::VerifyOrderRequest>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::VerifyOrder >::value();
  }
  static const char* value(const ::sushi_bot::VerifyOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushi_bot::VerifyOrderResponse> should match
// service_traits::MD5Sum< ::sushi_bot::VerifyOrder >
template<>
struct MD5Sum< ::sushi_bot::VerifyOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sushi_bot::VerifyOrder >::value();
  }
  static const char* value(const ::sushi_bot::VerifyOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushi_bot::VerifyOrderResponse> should match
// service_traits::DataType< ::sushi_bot::VerifyOrder >
template<>
struct DataType< ::sushi_bot::VerifyOrderResponse>
{
  static const char* value()
  {
    return DataType< ::sushi_bot::VerifyOrder >::value();
  }
  static const char* value(const ::sushi_bot::VerifyOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHI_BOT_MESSAGE_VERIFYORDER_H
