(cl:defpackage sushi_bot-srv
  (:use )
  (:export
   "MICROPHONE"
   "<MICROPHONE-REQUEST>"
   "MICROPHONE-REQUEST"
   "<MICROPHONE-RESPONSE>"
   "MICROPHONE-RESPONSE"
   "ROBOTTASK"
   "<ROBOTTASK-REQUEST>"
   "ROBOTTASK-REQUEST"
   "<ROBOTTASK-RESPONSE>"
   "ROBOTTASK-RESPONSE"
   "VERIFYORDER"
   "<VERIFYORDER-REQUEST>"
   "VERIFYORDER-REQUEST"
   "<VERIFYORDER-RESPONSE>"
   "VERIFYORDER-RESPONSE"
  ))

