// Generated by gencpp from file assignment_cogar/AssignTaskRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_ASSIGNTASKREQUEST_H
#define ASSIGNMENT_COGAR_MESSAGE_ASSIGNTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_cogar
{
template <class ContainerAllocator>
struct AssignTaskRequest_
{
  typedef AssignTaskRequest_<ContainerAllocator> Type;

  AssignTaskRequest_()
    : order_id()
    , robot_id()
    , dish_name()
    , table_id()  {
    }
  AssignTaskRequest_(const ContainerAllocator& _alloc)
    : order_id(_alloc)
    , robot_id(_alloc)
    , dish_name(_alloc)
    , table_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _order_id_type;
  _order_id_type order_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dish_name_type;
  _dish_name_type dish_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _table_id_type;
  _table_id_type table_id;





  typedef boost::shared_ptr< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AssignTaskRequest_

typedef ::assignment_cogar::AssignTaskRequest_<std::allocator<void> > AssignTaskRequest;

typedef boost::shared_ptr< ::assignment_cogar::AssignTaskRequest > AssignTaskRequestPtr;
typedef boost::shared_ptr< ::assignment_cogar::AssignTaskRequest const> AssignTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.order_id == rhs.order_id &&
    lhs.robot_id == rhs.robot_id &&
    lhs.dish_name == rhs.dish_name &&
    lhs.table_id == rhs.table_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_cogar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5debeed3ca11a92c1f4ac7da7fa0fecd";
  }

  static const char* value(const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5debeed3ca11a92cULL;
  static const uint64_t static_value2 = 0x1f4ac7da7fa0fecdULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_cogar/AssignTaskRequest";
  }

  static const char* value(const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string order_id\n"
"string robot_id\n"
"string dish_name\n"
"string table_id\n"
;
  }

  static const char* value(const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order_id);
      stream.next(m.robot_id);
      stream.next(m.dish_name);
      stream.next(m.table_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_cogar::AssignTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_cogar::AssignTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "order_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.order_id);
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
    s << indent << "dish_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dish_name);
    s << indent << "table_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.table_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_ASSIGNTASKREQUEST_H
