// Generated by gencpp from file assignment_cogar/AssignTask.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_ASSIGNTASK_H
#define ASSIGNMENT_COGAR_MESSAGE_ASSIGNTASK_H

#include <ros/service_traits.h>


#include <assignment_cogar/AssignTaskRequest.h>
#include <assignment_cogar/AssignTaskResponse.h>


namespace assignment_cogar
{

struct AssignTask
{

typedef AssignTaskRequest Request;
typedef AssignTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignTask
} // namespace assignment_cogar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_cogar::AssignTask > {
  static const char* value()
  {
    return "f47a80f63d9e9eca8fb4a2735112c7ca";
  }

  static const char* value(const ::assignment_cogar::AssignTask&) { return value(); }
};

template<>
struct DataType< ::assignment_cogar::AssignTask > {
  static const char* value()
  {
    return "assignment_cogar/AssignTask";
  }

  static const char* value(const ::assignment_cogar::AssignTask&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_cogar::AssignTaskRequest> should match
// service_traits::MD5Sum< ::assignment_cogar::AssignTask >
template<>
struct MD5Sum< ::assignment_cogar::AssignTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::AssignTask >::value();
  }
  static const char* value(const ::assignment_cogar::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::AssignTaskRequest> should match
// service_traits::DataType< ::assignment_cogar::AssignTask >
template<>
struct DataType< ::assignment_cogar::AssignTaskRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::AssignTask >::value();
  }
  static const char* value(const ::assignment_cogar::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_cogar::AssignTaskResponse> should match
// service_traits::MD5Sum< ::assignment_cogar::AssignTask >
template<>
struct MD5Sum< ::assignment_cogar::AssignTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::AssignTask >::value();
  }
  static const char* value(const ::assignment_cogar::AssignTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::AssignTaskResponse> should match
// service_traits::DataType< ::assignment_cogar::AssignTask >
template<>
struct DataType< ::assignment_cogar::AssignTaskResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::AssignTask >::value();
  }
  static const char* value(const ::assignment_cogar::AssignTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_ASSIGNTASK_H
