// Generated by gencpp from file assignment_cogar/FoodPlacer.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_FOODPLACER_H
#define ASSIGNMENT_COGAR_MESSAGE_FOODPLACER_H

#include <ros/service_traits.h>


#include <assignment_cogar/FoodPlacerRequest.h>
#include <assignment_cogar/FoodPlacerResponse.h>


namespace assignment_cogar
{

struct FoodPlacer
{

typedef FoodPlacerRequest Request;
typedef FoodPlacerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FoodPlacer
} // namespace assignment_cogar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_cogar::FoodPlacer > {
  static const char* value()
  {
    return "5a619c9ede21322d453b3bcb4c37ad47";
  }

  static const char* value(const ::assignment_cogar::FoodPlacer&) { return value(); }
};

template<>
struct DataType< ::assignment_cogar::FoodPlacer > {
  static const char* value()
  {
    return "assignment_cogar/FoodPlacer";
  }

  static const char* value(const ::assignment_cogar::FoodPlacer&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_cogar::FoodPlacerRequest> should match
// service_traits::MD5Sum< ::assignment_cogar::FoodPlacer >
template<>
struct MD5Sum< ::assignment_cogar::FoodPlacerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::FoodPlacer >::value();
  }
  static const char* value(const ::assignment_cogar::FoodPlacerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::FoodPlacerRequest> should match
// service_traits::DataType< ::assignment_cogar::FoodPlacer >
template<>
struct DataType< ::assignment_cogar::FoodPlacerRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::FoodPlacer >::value();
  }
  static const char* value(const ::assignment_cogar::FoodPlacerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_cogar::FoodPlacerResponse> should match
// service_traits::MD5Sum< ::assignment_cogar::FoodPlacer >
template<>
struct MD5Sum< ::assignment_cogar::FoodPlacerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::FoodPlacer >::value();
  }
  static const char* value(const ::assignment_cogar::FoodPlacerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::FoodPlacerResponse> should match
// service_traits::DataType< ::assignment_cogar::FoodPlacer >
template<>
struct DataType< ::assignment_cogar::FoodPlacerResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::FoodPlacer >::value();
  }
  static const char* value(const ::assignment_cogar::FoodPlacerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_FOODPLACER_H
