// Generated by gencpp from file assignment_cogar/FoodPlacerRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_FOODPLACERREQUEST_H
#define ASSIGNMENT_COGAR_MESSAGE_FOODPLACERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_cogar
{
template <class ContainerAllocator>
struct FoodPlacerRequest_
{
  typedef FoodPlacerRequest_<ContainerAllocator> Type;

  FoodPlacerRequest_()
    : status()
    , has_empty_plate(false)
    , robot_id()  {
    }
  FoodPlacerRequest_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , has_empty_plate(false)
    , robot_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef uint8_t _has_empty_plate_type;
  _has_empty_plate_type has_empty_plate;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FoodPlacerRequest_

typedef ::assignment_cogar::FoodPlacerRequest_<std::allocator<void> > FoodPlacerRequest;

typedef boost::shared_ptr< ::assignment_cogar::FoodPlacerRequest > FoodPlacerRequestPtr;
typedef boost::shared_ptr< ::assignment_cogar::FoodPlacerRequest const> FoodPlacerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator1> & lhs, const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.has_empty_plate == rhs.has_empty_plate &&
    lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator1> & lhs, const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_cogar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e89321cf6c1920138b6326a67aa76960";
  }

  static const char* value(const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe89321cf6c192013ULL;
  static const uint64_t static_value2 = 0x8b6326a67aa76960ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_cogar/FoodPlacerRequest";
  }

  static const char* value(const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"bool has_empty_plate\n"
"string robot_id\n"
;
  }

  static const char* value(const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.has_empty_plate);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FoodPlacerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_cogar::FoodPlacerRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "has_empty_plate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_empty_plate);
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_FOODPLACERREQUEST_H
