// Generated by gencpp from file assignment_cogar/MicrophoneRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_MICROPHONEREQUEST_H
#define ASSIGNMENT_COGAR_MESSAGE_MICROPHONEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_cogar
{
template <class ContainerAllocator>
struct MicrophoneRequest_
{
  typedef MicrophoneRequest_<ContainerAllocator> Type;

  MicrophoneRequest_()
    {
    }
  MicrophoneRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MicrophoneRequest_

typedef ::assignment_cogar::MicrophoneRequest_<std::allocator<void> > MicrophoneRequest;

typedef boost::shared_ptr< ::assignment_cogar::MicrophoneRequest > MicrophoneRequestPtr;
typedef boost::shared_ptr< ::assignment_cogar::MicrophoneRequest const> MicrophoneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace assignment_cogar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assignment_cogar::MicrophoneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_cogar/MicrophoneRequest";
  }

  static const char* value(const ::assignment_cogar::MicrophoneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
;
  }

  static const char* value(const ::assignment_cogar::MicrophoneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MicrophoneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_cogar::MicrophoneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::assignment_cogar::MicrophoneRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_MICROPHONEREQUEST_H
