// Generated by gencpp from file assignment_cogar/Microphone.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_MICROPHONE_H
#define ASSIGNMENT_COGAR_MESSAGE_MICROPHONE_H

#include <ros/service_traits.h>


#include <assignment_cogar/MicrophoneRequest.h>
#include <assignment_cogar/MicrophoneResponse.h>


namespace assignment_cogar
{

struct Microphone
{

typedef MicrophoneRequest Request;
typedef MicrophoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Microphone
} // namespace assignment_cogar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_cogar::Microphone > {
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::assignment_cogar::Microphone&) { return value(); }
};

template<>
struct DataType< ::assignment_cogar::Microphone > {
  static const char* value()
  {
    return "assignment_cogar/Microphone";
  }

  static const char* value(const ::assignment_cogar::Microphone&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_cogar::MicrophoneRequest> should match
// service_traits::MD5Sum< ::assignment_cogar::Microphone >
template<>
struct MD5Sum< ::assignment_cogar::MicrophoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::Microphone >::value();
  }
  static const char* value(const ::assignment_cogar::MicrophoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::MicrophoneRequest> should match
// service_traits::DataType< ::assignment_cogar::Microphone >
template<>
struct DataType< ::assignment_cogar::MicrophoneRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::Microphone >::value();
  }
  static const char* value(const ::assignment_cogar::MicrophoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_cogar::MicrophoneResponse> should match
// service_traits::MD5Sum< ::assignment_cogar::Microphone >
template<>
struct MD5Sum< ::assignment_cogar::MicrophoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::Microphone >::value();
  }
  static const char* value(const ::assignment_cogar::MicrophoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::MicrophoneResponse> should match
// service_traits::DataType< ::assignment_cogar::Microphone >
template<>
struct DataType< ::assignment_cogar::MicrophoneResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::Microphone >::value();
  }
  static const char* value(const ::assignment_cogar::MicrophoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_MICROPHONE_H
