// Generated by gencpp from file assignment_cogar/OrderStatus.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_ORDERSTATUS_H
#define ASSIGNMENT_COGAR_MESSAGE_ORDERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_cogar
{
template <class ContainerAllocator>
struct OrderStatus_
{
  typedef OrderStatus_<ContainerAllocator> Type;

  OrderStatus_()
    : robot_id()
    , dish_name()
    , status()
    , requires_staff_attention(false)  {
    }
  OrderStatus_(const ContainerAllocator& _alloc)
    : robot_id(_alloc)
    , dish_name(_alloc)
    , status(_alloc)
    , requires_staff_attention(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dish_name_type;
  _dish_name_type dish_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef uint8_t _requires_staff_attention_type;
  _requires_staff_attention_type requires_staff_attention;





  typedef boost::shared_ptr< ::assignment_cogar::OrderStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_cogar::OrderStatus_<ContainerAllocator> const> ConstPtr;

}; // struct OrderStatus_

typedef ::assignment_cogar::OrderStatus_<std::allocator<void> > OrderStatus;

typedef boost::shared_ptr< ::assignment_cogar::OrderStatus > OrderStatusPtr;
typedef boost::shared_ptr< ::assignment_cogar::OrderStatus const> OrderStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_cogar::OrderStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_cogar::OrderStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_cogar::OrderStatus_<ContainerAllocator1> & lhs, const ::assignment_cogar::OrderStatus_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.dish_name == rhs.dish_name &&
    lhs.status == rhs.status &&
    lhs.requires_staff_attention == rhs.requires_staff_attention;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_cogar::OrderStatus_<ContainerAllocator1> & lhs, const ::assignment_cogar::OrderStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_cogar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::OrderStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::OrderStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::OrderStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53d9d96d6078b16a5b79f0e97d7da161";
  }

  static const char* value(const ::assignment_cogar::OrderStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53d9d96d6078b16aULL;
  static const uint64_t static_value2 = 0x5b79f0e97d7da161ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_cogar/OrderStatus";
  }

  static const char* value(const ::assignment_cogar::OrderStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_id\n"
"string dish_name\n"
"string status\n"
"bool requires_staff_attention\n"
;
  }

  static const char* value(const ::assignment_cogar::OrderStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.dish_name);
      stream.next(m.status);
      stream.next(m.requires_staff_attention);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrderStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_cogar::OrderStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_cogar::OrderStatus_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
    s << indent << "dish_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dish_name);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "requires_staff_attention: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.requires_staff_attention);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_ORDERSTATUS_H
