// Generated by gencpp from file assignment_cogar/TriggerAnalysis.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSIS_H
#define ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSIS_H

#include <ros/service_traits.h>


#include <assignment_cogar/TriggerAnalysisRequest.h>
#include <assignment_cogar/TriggerAnalysisResponse.h>


namespace assignment_cogar
{

struct TriggerAnalysis
{

typedef TriggerAnalysisRequest Request;
typedef TriggerAnalysisResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerAnalysis
} // namespace assignment_cogar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_cogar::TriggerAnalysis > {
  static const char* value()
  {
    return "79fe38de1d07cd33dda0cbb43e0bafa8";
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysis&) { return value(); }
};

template<>
struct DataType< ::assignment_cogar::TriggerAnalysis > {
  static const char* value()
  {
    return "assignment_cogar/TriggerAnalysis";
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysis&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_cogar::TriggerAnalysisRequest> should match
// service_traits::MD5Sum< ::assignment_cogar::TriggerAnalysis >
template<>
struct MD5Sum< ::assignment_cogar::TriggerAnalysisRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::TriggerAnalysis >::value();
  }
  static const char* value(const ::assignment_cogar::TriggerAnalysisRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::TriggerAnalysisRequest> should match
// service_traits::DataType< ::assignment_cogar::TriggerAnalysis >
template<>
struct DataType< ::assignment_cogar::TriggerAnalysisRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::TriggerAnalysis >::value();
  }
  static const char* value(const ::assignment_cogar::TriggerAnalysisRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_cogar::TriggerAnalysisResponse> should match
// service_traits::MD5Sum< ::assignment_cogar::TriggerAnalysis >
template<>
struct MD5Sum< ::assignment_cogar::TriggerAnalysisResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::TriggerAnalysis >::value();
  }
  static const char* value(const ::assignment_cogar::TriggerAnalysisResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::TriggerAnalysisResponse> should match
// service_traits::DataType< ::assignment_cogar::TriggerAnalysis >
template<>
struct DataType< ::assignment_cogar::TriggerAnalysisResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::TriggerAnalysis >::value();
  }
  static const char* value(const ::assignment_cogar::TriggerAnalysisResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSIS_H
