// Generated by gencpp from file assignment_cogar/TriggerAnalysisRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSISREQUEST_H
#define ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSISREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_cogar
{
template <class ContainerAllocator>
struct TriggerAnalysisRequest_
{
  typedef TriggerAnalysisRequest_<ContainerAllocator> Type;

  TriggerAnalysisRequest_()
    : robot_id()  {
    }
  TriggerAnalysisRequest_(const ContainerAllocator& _alloc)
    : robot_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerAnalysisRequest_

typedef ::assignment_cogar::TriggerAnalysisRequest_<std::allocator<void> > TriggerAnalysisRequest;

typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisRequest > TriggerAnalysisRequestPtr;
typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisRequest const> TriggerAnalysisRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator1> & lhs, const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator1> & lhs, const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_cogar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd64f744797bf092ea73be78956cc35c";
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd64f744797bf092ULL;
  static const uint64_t static_value2 = 0xea73be78956cc35cULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_cogar/TriggerAnalysisRequest";
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_id\n"
;
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerAnalysisRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_cogar::TriggerAnalysisRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSISREQUEST_H
