// Generated by gencpp from file assignment_cogar/TriggerAnalysisResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSISRESPONSE_H
#define ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSISRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_cogar
{
template <class ContainerAllocator>
struct TriggerAnalysisResponse_
{
  typedef TriggerAnalysisResponse_<ContainerAllocator> Type;

  TriggerAnalysisResponse_()
    : success(false)  {
    }
  TriggerAnalysisResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerAnalysisResponse_

typedef ::assignment_cogar::TriggerAnalysisResponse_<std::allocator<void> > TriggerAnalysisResponse;

typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisResponse > TriggerAnalysisResponsePtr;
typedef boost::shared_ptr< ::assignment_cogar::TriggerAnalysisResponse const> TriggerAnalysisResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator1> & lhs, const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator1> & lhs, const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_cogar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_cogar/TriggerAnalysisResponse";
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerAnalysisResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_cogar::TriggerAnalysisResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_TRIGGERANALYSISRESPONSE_H
