// Generated by gencpp from file assignment_cogar/VerifyOrder.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_COGAR_MESSAGE_VERIFYORDER_H
#define ASSIGNMENT_COGAR_MESSAGE_VERIFYORDER_H

#include <ros/service_traits.h>


#include <assignment_cogar/VerifyOrderRequest.h>
#include <assignment_cogar/VerifyOrderResponse.h>


namespace assignment_cogar
{

struct VerifyOrder
{

typedef VerifyOrderRequest Request;
typedef VerifyOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VerifyOrder
} // namespace assignment_cogar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_cogar::VerifyOrder > {
  static const char* value()
  {
    return "821c392785703a596b403147fefd576d";
  }

  static const char* value(const ::assignment_cogar::VerifyOrder&) { return value(); }
};

template<>
struct DataType< ::assignment_cogar::VerifyOrder > {
  static const char* value()
  {
    return "assignment_cogar/VerifyOrder";
  }

  static const char* value(const ::assignment_cogar::VerifyOrder&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_cogar::VerifyOrderRequest> should match
// service_traits::MD5Sum< ::assignment_cogar::VerifyOrder >
template<>
struct MD5Sum< ::assignment_cogar::VerifyOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::VerifyOrder >::value();
  }
  static const char* value(const ::assignment_cogar::VerifyOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::VerifyOrderRequest> should match
// service_traits::DataType< ::assignment_cogar::VerifyOrder >
template<>
struct DataType< ::assignment_cogar::VerifyOrderRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::VerifyOrder >::value();
  }
  static const char* value(const ::assignment_cogar::VerifyOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_cogar::VerifyOrderResponse> should match
// service_traits::MD5Sum< ::assignment_cogar::VerifyOrder >
template<>
struct MD5Sum< ::assignment_cogar::VerifyOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_cogar::VerifyOrder >::value();
  }
  static const char* value(const ::assignment_cogar::VerifyOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_cogar::VerifyOrderResponse> should match
// service_traits::DataType< ::assignment_cogar::VerifyOrder >
template<>
struct DataType< ::assignment_cogar::VerifyOrderResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_cogar::VerifyOrder >::value();
  }
  static const char* value(const ::assignment_cogar::VerifyOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_COGAR_MESSAGE_VERIFYORDER_H
