(cl:defpackage assignments-srv
  (:use )
  (:export
   "CHECKJOINTSTATE"
   "<CHECKJOINTSTATE-REQUEST>"
   "CHECKJOINTSTATE-REQUEST"
   "<CHECKJOINTSTATE-RESPONSE>"
   "CHECKJOINTSTATE-RESPONSE"
   "SPEAKER"
   "<SPEAKER-REQUEST>"
   "SPEAKER-REQUEST"
   "<SPEAKER-RESPONSE>"
   "SPEAKER-RESPONSE"
  ))

